### ISSUE TITLE
use as generative model (text -> svg)

### ISSUE THREAD

**Issue by benswift** [emreaksan/deepwriting#12]
I've got the `visualise_hw.py` script working correctly (as described in the readme). What's the best/easiest way to use the pre-trained model to generate the data (either as a svg, or even better as `<key, value>` pair stroke data.

Thanks for the help.

**Comment by Yashwanthv21** [comment]
@benswift did the code run as it is or did you change something. I am trying to run the code.

**Comment by benswift** [comment]
I made a few small tweaks to get it to install with [pipenv](https://pipenv.readthedocs.io/en/latest/), you can see them in [my fork](https://github.com/benswift/deepwriting/).

After that, it worked as described in the readme, e.g. this will generate "handwriting" svgs for the first 3 phrases in the dictionary (index 0, 1 and 2).

```
PYTHONPATH=$PYTHONPATH:./source pipenv run python visualize_hw.py -D ./data/deepwriting_validation.npz -O ./data_images -S 0 1 2
```
