### ISSUE TITLE
Timestamp information or sampling rate

### ISSUE THREAD

**Issue by Srinivas-R** [emreaksan/deepwriting#18]
Thank you for this excellent work, as well as the valuable dataset. I've been trying to find any information about the timestamps for each stroke point, or a sampling rate. I think the original IAM-OnDB had timestamps, but even a sampling rate (if the stroke points are picked after regular intervals) for this dataset would be sufficient.

I'd appreciate any help you can provide in this regard. Thanks!

**Comment by emreaksan** [comment]
Hi,

We released an extended version of our dataset which includes timestamp information as well. Please visit our project page https://ait.ethz.ch/projects/2018/deepwriting/
