### ISSUE TITLE
Data link is dead

### ISSUE THREAD

**Issue by morrowa** [emreaksan/deepwriting#22]
The link to the preprocessed data in the readme (https://ait.ethz.ch/projects/2018/deepwriting/downloads/deepwriting_dataset.tar.gz) now returns HTTP 404. Is a new link available?

**Comment by hyunwoona** [comment]
Oh no

**Comment by emreaksan** [comment]
Thanks for the signal. Links are fixed now. You can also check out the project page for the raw dataset: https://ait.ethz.ch/deepwriting
